### ISSUE TITLE
Adding promos to IKO sheet makes for duplicates

### ISSUE THREAD

**Issue by fverdoja** [taw/magic-sealed-data#10] opened 2021-03-15 10:44 UTC
This might not necessarily an issue, but by introducing promos in IKO sheets now simply choosing n cards from a sheet doesn't guarantee lack of duplicates anymore. This has never been the case with any other sheet iirc. This requires users to check for duplicates now. Especially since, I assume, showcase and other promos will progressively be added to the other sets with them (ELD forward).

A workaround could be to implement promos as separate promo sheets (one for each rarity) with some probability of replacing one of the cards of the same rarity from the booster... does this sound doable?

I personally think it would be nice to preserve the lack of duplicates on sheets if possible.

**Comment by taw** [comment] 2021-03-15 10:58
So yeah, I sort of plan to add showcase cards for every set that has them, and that's going to be pretty much every one of them. The main reason that's not done yet is that it's really hard to find exact rules, and every set does showcase cards differently.

It would even be nice to do those set / collector / vip / whatever boosters, but that's even less documented, so I probably won't do that unless someone helps.

Anyway, in current data format we just have no way of expressing "no duplicate of different printings of the same card". Putting them on separate sheet wouldn't do anything since the duplicate risk is between showcase and non-showcase version of the same card.

It would need totally restructuring the data format, and I'm not even sure how that would work (like, a list of "don't put those combinations of printings in one booster"?).

>  with some probability of replacing one of the cards of the same rarity from the booster

Showcase cards just go onto same print sheet as regular cards. They work more like basic lands and not at all like foils.

**Comment by fverdoja** [comment] 2021-03-15 14:43
Yes, you are right, my proposal doesn't actually fix the duplicate issue... 😅 

How about having the data in the sheet be reflective of the "base card" and then for cards which might upgrade to a showcase have their value be a list of all variations, with relative weight? Something like:
```json
...
"iko:112": {
    "weight": 1,
    "variations": {
        "iko:112": 3,
        "iko:291": 1
    }
}
...
```
This way people using the sheet don't need to worry about duplicates, and, if they don't care about card variations, they can just read the base card with its weight, and if they do care about variations they can, once they picked a card with variations, check if they should put in the booster the base card or the alternative one according to their relative weights.

I understand it's a bit of refactoring though, and maybe you are less concerned than I am about duplicates... 😄

**Comment by taw** [comment] 2021-03-26 02:44
I did not verify it yet, but I think the following deduplication algorithm would work:

* while generating a booster, if you get another card with the same name and foil status, reroll that card

So X + foil of X is fine; but X + showcase of X is not.

I cannot think of any booster than violates this rule, but I'd need to double check.

The `variations` block would really complicate json, while being (as far as I can tell) basically be list of printings with the same name.

If there's no counter-examples (still needs checking), then just documenting this should be enough.

**Comment by taw** [comment] 2021-03-26 17:21
OK, so here's the final correct rule:

* do not pick more than one card with same name from same sheet

I need to document it everywhere and implement it on mtg.wtf too.

Duplicates between sheets are definitely possible in real boosters (but that only affects really old sets: LEA, LEB, 2ED, 3ED, ATQ).

**Comment by fverdoja** [comment] 2021-03-26 17:40
Yeah that's how I have it implemented now in Booster Tutor, but I think it would be nice to document the change (also maybe on mtgjson side?), since before this check was not needed.

**Comment by taw** [comment] 2021-03-26 17:46
There's a lot more affected sets, but most of them were from super early days. From new ones CHK and UST are the only sets for which this rule is needed. (as well as IKO and every set going forward; once I implement showcase cards for them)

**Comment by fverdoja** [comment] 2021-03-26 18:20
How about adding a `has_duplicates` property to sheets with duplicates? Similarly to the `balance_colors`...

**Comment by taw** [comment] 2021-03-26 19:22
Right now, deduplicating by name works with everything. You don't need multiple algorithms.

**Comment by taw** [comment] 2021-03-26 19:35
Oh damn it. Actually, there is one set which would need special treatment - UST.

There are cards which have different names, but should be treated as same for deduplication.

Group:
* Garbage Elemental (a)	
* Garbage Elemental (b)	
* Garbage Elemental (c)	
* Garbage Elemental (d)	
* Garbage Elemental (e)	
* Garbage Elemental (f)	

Group:
* Knight of the Kitchen Sink (a)	
* Knight of the Kitchen Sink (b)	
* Knight of the Kitchen Sink (c)	
* Knight of the Kitchen Sink (d)	
* Knight of the Kitchen Sink (e)	
* Knight of the Kitchen Sink (f)	

Group:
* Sly Spy (a)	
* Sly Spy (b)	
* Sly Spy (c)	
* Sly Spy (d)	
* Sly Spy (e)	
* Sly Spy (f)	

Group:
* Curious Killbot	
* Delighted Killbot	
* Despondent Killbot	
* Enraged Killbot

First 3 groups have same printed name (but unique Gatherer / mtg.wtf names).

Last group has different names even printed, but it's treated as one card for purpose of collation.

Now dedupliaction-by-name will already make UST better, as it will correctly deduplicate all cards with art variants, so I think we can live with occasional pack incorrectly having two Killbots.

Deduplication-by-name correctly handles every other booster ever as far as I can tell.

(I've also been told some non-draft boosters like theme boosters intentionally contain duplicated cards, but they currently aren't covered. Also Jumpstart boosters contain many duplicates, but these are listed as 121 20-card precons not as boosters. So in both cases, out of scope.)

**Comment by fverdoja** [comment] 2021-03-26 20:22
Thanks a lot for the level of care you are dedicating to this issue, for what is worth I agree with all your conclusions. The check you propose is the best solution for practically all situations, and if the corner case is in an UN-set, I think it can be accepted. Also, if someone really cares about it, it's also not impossible to implement an ad-hoc check for UST, but I will definitely not implement it for Booster Tutor. :)

**Comment by taw** [comment] 2021-03-26 22:23
There are far more important things to fix before I care about duplicate Killbots, starting from showcase cards for remaining sets.

**Comment by taw** [comment] 2021-03-27 15:59
I updated documentation in https://github.com/taw/magic-sealed-data (Recommended Algorithms section)

Not sure how clear this is.

**Comment by fverdoja** [comment] 2021-03-29 08:12
It's very understandable to me. I would consider this closed. 
Thanks for taking care of clarifying this.

**Comment by taw** [comment] 2021-03-29 09:58
All right, closing this.

**Closed as completed by taw** 2021-03-29 09:58 UTC
